name: flutter_listin
description: Listin - Feira Fácil!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Nativo
  cupertino_icons: ^1.0.2

  # Outros pacotes
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: "^0.13.1"
  uuid: ^4.3.3

  # Pacotes do curso
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - "assets/" 

flutter_native_splash:
  color: "#cce663"
  image: assets/logo.png
  android_12:
    color: "#cce663"
    icon_background_color: "#cce663"
    image: assets/logo_1152.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21